### PR TITLE
Don't alter file paths when playing back recordings

### PR DESCRIPTION
**Pull request by benlangfeld**

### CODE REVIEW

**Comment by benlangfeld** [comment]
This will now, I suspect, work on FS/mod_rayo but not Asterisk. We need to define this behaviour properly. Should the Asterisk output component in Punchblock strip the file:// scheme and file extension? I think it probably should to be more compatible with Rayo which requires support for full URIs.

**Comment by bklang** [comment]
I'm inclined to agree that the output component should take a normalized file URL and prepare it for playback on Asterisk.  However, can we do this in a backward compatible way?

**Comment by benlangfeld** [comment]
So, we already strip `file://` on Asterisk, so that's not a problem in PB 2.0. I've added support for stripping off file extensions in https://github.com/adhearsion/punchblock/pull/173 but I'd appreciate a review of that.

**Comment by JustinAiken** [comment]
Also, if I remember off the top of my head, certain TTS engines in Asterisk _cough Cepstral cough_ also had a different format required than Asterisk native...

**Pull request merged**
