### PR TITLE
FreeSwitch and further updates to adhearsion-voicemail

### PR DESCRIPTION
**Pull request by emcgee**
This goes across several different parts of the voicemail system, but tunes it more closely for FreeSWITCH.

### CODE REVIEW

**Comment by benlangfeld** [comment]
Thanks! I'll review this next week after Justin has finished his rounds on the plugin. Some of the tricks to render complex types (ordinals, dates, etc) is being worked into Adhearsion core and other parts are redundant on FS with mod_rayo.

**Comment by emcgee** [comment]
No worries, sounds great! There are also a couple of specific commits that people may want, like <a href="https://github.com/ringplus/voicemail/commit/dbdb4360ff867bf82db8fa9f693b6a7e623e6c02">dbd436</a>.

We use it because connecting costs users money/min, and if somebody hangs up during the greeting there are no connection costs - but the 183 may cause a hidden issue with non-standard farside implementations.

**Comment by JustinAiken** [comment]
Oh, haha... step out for lunch, come back to find that much of what I'd planned for this afternoon has been done already :)

I think that the `#answer` thing should be configurable - the 183 thing may or may not work for everything... other than that, let's merge this in, and I'll start on `0.2.0`, which will require adhearsion 2.4.0 for it's new methods, and get rid of some platform iffyness...

EDIT - Files changed, 0?  What's up with that, github!?

**Comment by benlangfeld** [comment]
Ooh, no Justin, please don't merge all of this!

**Comment by JustinAiken** [comment]
Okay, I've been picking through these, and merged what I think is critical:
- Fixed any bugs that would result in a crash
- Only record one end 
- Allow passing of the storage layer

The rest I've left out for now.. I'm going to call this 0.1.0, and work on a better native integration with freeswitch for 0.2.0 - going to use ahn 2.4.0's new `#say_characters` instead of ahn_say and the such

Keeping this PR open, because there's some ideas that should be revisited here - when to `#answer`, record timeout (should actually be a configurable option), etc..

**Comment by benlangfeld** [comment]
So right now it looks like there's two issues remaining from this:
- When to answer. Ticket opened at https://github.com/adhearsion/voicemail/issues/12.
- Playback and file extensions. On Asterisk it's necessary to remove file extensions and on FS/rayo it's not. PR at https://github.com/adhearsion/voicemail/pull/13

I'm going to close this since there doesn't seem to be anything left here that doesn't have a better home. Thanks for starting this off Evan :)

**Pull request closed without merging**
