### PR TITLE
Prompt returns vs. hangup, and guards

### PR DESCRIPTION
**Pull request by emcgee**
There are a number of places where we are hanging up on a caller if they fail a menu structure. In my mind, this should only happen on the main_menu -- any section_menu (or lower tier) should fall back to the previous higher tier. 

Only main_menu should be able to issue the final `hangup.`

### CODE REVIEW

**Comment by bklang** [comment]
Looks good to me.  @JustinAiken @polysics any thoughts?

**Comment by JustinAiken** [comment]
Looks good, but would be nice if it could play the "All of your new messages have been successfully deleted" message via either the config prompt or the I18n; otherwise international users won't be able to use this...

**Comment by emcgee** [comment]
@JustinAiken Wouldn't this line pull from I18n if `use_i18n` is true?
https://github.com/emcgee/voicemail/blob/6b2dd63dd46dc403ba4abce33cd5b54d4f809958/lib/voicemail/call_controllers/mailbox_cleaner_controller.rb#L30

**Comment by JustinAiken** [comment]
Oh yes true... been so long since worked on this, that I forgot I made a nice method to magically do that... explicit `I18n.t` calls are only needed if there's something different in the prompt (like interpolation or time/date formatting)... But could you add strings to the [en.yml](https://github.com/adhearsion/voicemail/blob/develop/templates/en.yml) template whenever you add them to the ever-growing config hash?

**Comment by emcgee** [comment]
Absolutely. :boom:

**Comment by JustinAiken** [comment]
Thanks :) :+1: :ship:

**Comment by bklang** [comment]
Just waiting on Travis

**Pull request merged**
