### PR TITLE
Configurable I18n provider

### PR DESCRIPTION
**Pull request by CodeMangler**
- Allows assigning a custom I18n provider to be used for resolving I18n keys

(Not sure why all the merge commits are being listed as part of this PR)

### CODE REVIEW

**Comment by benlangfeld** [comment]
The merge commits are here because your branch was based on master. Please rebase on develop.

**Comment by bklang** [comment]
I'm going to close this in favor of a PR (coming shortly) that will take advantage of [adhearsion-i18n](https://github.com/adhearsion/adhearsion-i18n).

**Comment by CodeMangler** [comment]
@bklang would the new PR allow some way to interpolate custom variables in the audio URL? Like "http://%{some_var}.foo.bar/%{another_var}"
That was the primary thing we needed this for in GH.

**Comment by bklang** [comment]
@CodeMangler [adhearsion-i18n](https://github.com/adhearsion/adhearsion-i18n) uses the standard [Rails I18n library](https://rubygems.org/gems/i18n), which itself does support interpolation ([docs](http://guides.rubyonrails.org/i18n.html#interpolation)).  So yes, it should (though I've not personally tested it).  If you experience any problems with Adhearsion-i18n, issues are welcome over there.

**Pull request closed without merging**
